export const mockAssignments = [
  {
    "id": "ASN-1001",
    "title": "Quadratic Equations Practice",
    "description": "Solve exercise 4.1 completely.",
    "subjectId": "SUB-MATH",
    "subject": "Mathematics",
    "classId": "10A",
    "className": "Class 10",
    "section": "A",
    "type": "Homework",
    "createdDate": "2026-07-25",
    "dueDate": "2026-07-30",
    "totalMarks": 50,
    "instructions": "Show all steps clearly.",
    "status": "Published",
    "departmentId": 2,
    "teacherId": 102
  },
  {
    "id": "ASN-1002",
    "title": "Trigonometry Basics",
    "description": "Learn formulas and solve exercise 8.1",
    "subjectId": "SUB-MATH",
    "subject": "Mathematics",
    "classId": "9B",
    "className": "Class 9",
    "section": "B",
    "type": "Classwork",
    "createdDate": "2026-07-28",
    "dueDate": "2026-07-29",
    "totalMarks": 20,
    "instructions": "Submit before class ends.",
    "status": "Draft",
    "departmentId": 2,
    "teacherId": 102
  },
  {
    "id": "ASN-1003",
    "title": "Python Basics",
    "description": "Write a python script for calculator",
    "subjectId": "SUB-CS",
    "subject": "Computer Science",
    "classId": "11C",
    "className": "Class 11",
    "section": "C",
    "type": "Project",
    "createdDate": "2026-07-20",
    "dueDate": "2026-08-05",
    "totalMarks": 100,
    "instructions": "Upload the .py file.",
    "status": "Published",
    "departmentId": 3,
    "teacherId": 103
  }
];
