export const mockStudents = [
  {
    "studentId": "STD-001",
    "studentName": "Arun Kumar",
    "classId": "10A",
    "className": "Class 10",
    "section": "A",
    "rollNumber": "01",
    "departmentId": 2,
    "email": "arun.k@student.edu",
    "phone": "+91 8887776661",
    "address": "123 Math St",
    "emergencyContact": "+91 9998887771",
    "notes": "Excellent at algebra.",
    "attendancePercentage": 95,
    "performancePercentage": 92,
    "status": "Active",
    "dateOfBirth": "2010-05-15",
    "parentName": "Suresh Kumar",
    "photoUrl": "assets/images/student1.jpg"
  },
  {
    "studentId": "STD-002",
    "studentName": "Meera Reddy",
    "classId": "10A",
    "className": "Class 10",
    "section": "A",
    "rollNumber": "02",
    "departmentId": 2,
    "email": "meera.r@student.edu",
    "phone": "+91 8887776662",
    "address": "456 Geometry Ave",
    "emergencyContact": "+91 9998887772",
    "notes": "Needs help with trigonometry.",
    "attendancePercentage": 85,
    "performancePercentage": 78,
    "status": "Active",
    "dateOfBirth": "2010-08-22",
    "parentName": "Krishna Reddy",
    "photoUrl": "assets/images/student2.jpg"
  },
  {
    "studentId": "STD-003",
    "studentName": "Rahul Sharma",
    "classId": "9B",
    "className": "Class 9",
    "section": "B",
    "rollNumber": "15",
    "departmentId": 2,
    "email": "rahul.s@student.edu",
    "phone": "+91 8887776663",
    "address": "789 Algebra Blvd",
    "emergencyContact": "+91 9998887773",
    "notes": "",
    "attendancePercentage": 72,
    "performancePercentage": 65,
    "status": "Active",
    "dateOfBirth": "2011-02-10",
    "parentName": "Vijay Sharma",
    "photoUrl": "assets/images/student3.jpg"
  },
  {
    "studentId": "STD-004",
    "studentName": "Fathima Khan",
    "classId": "11C",
    "className": "Class 11",
    "section": "C",
    "rollNumber": "05",
    "departmentId": 3,
    "email": "fathima.k@student.edu",
    "phone": "+91 8887776664",
    "address": "101 Code Ln",
    "emergencyContact": "+91 9998887774",
    "notes": "CS Student, should not be visible to Math teacher.",
    "attendancePercentage": 98,
    "performancePercentage": 95,
    "status": "Active",
    "dateOfBirth": "2009-11-05",
    "parentName": "Imran Khan",
    "photoUrl": "assets/images/student4.jpg"
  }
];
